### ISSUE TITLE
1481-17 

### ISSUE THREAD

**Issue by Rimmuru** [Halen84/RDR3-Decompiled-Scripts#1]
would you consider updating for 1491-17 update?
also how did you download them?, I'm not seeing them under https://prod.cloud.rockstargames.com/titles/rdr2/pcros/bgscripts/bg_ng_1491_17.rpf

**Comment by Halen84** [comment]
Sorry, didn't see this until now. I'll update them soon though I'm not sure if much changed in the scripts. I just downloaded them w/ OpenIV
